version: 2

# Include submodules.
submodules:
  include: all

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats: []

# Installs the package and the docs requirements.
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_install:
      - make patch-thirdparty
