version: 2.1

executors:
  executor:
    machine:
        image: ubuntu-1604:201903-01

jobs:
  build:
      executor: executor
      steps:
        - checkout
        - run:
            name: Build container
            command: make build
        - run:
            name: Run tests
            command: make test
  